//
// Created by bohdan on 06.02.26.
//

#include "Volt/Core/Lexer/Token.h"
#include "Volt/Core/CompilationContext/CompilationContext.h"
#include <sstream>

#define GEN_CASE_TO_STRING(Op) case Op: TypeStr = #Op; break;

namespace Volt
{
	std::string Token::ToString(const CompilationContext &Context) const
	{
		std::string TypeStr;

		switch (Type)
		{
			GEN_CASE_TO_STRING(IDENTIFIER)
			GEN_CASE_TO_STRING(BYTE_NUMBER)
			GEN_CASE_TO_STRING(INT_NUMBER)
			GEN_CASE_TO_STRING(LONG_NUMBER)
			GEN_CASE_TO_STRING(FLOAT_NUMBER)
			GEN_CASE_TO_STRING(DOUBLE_NUMBER)
			GEN_CASE_TO_STRING(STRING)
			GEN_CASE_TO_STRING(BOOL_TRUE)
			GEN_CASE_TO_STRING(BOOL_FALSE)
			GEN_CASE_TO_STRING(CHAR)
			GEN_CASE_TO_STRING(OP_ADD)
			GEN_CASE_TO_STRING(OP_SUB)
			GEN_CASE_TO_STRING(OP_MUL)
			GEN_CASE_TO_STRING(OP_DIV)
			GEN_CASE_TO_STRING(OP_MOD)
			GEN_CASE_TO_STRING(OP_INC)
			GEN_CASE_TO_STRING(OP_DEC)
			GEN_CASE_TO_STRING(OP_ASSIGN)
			GEN_CASE_TO_STRING(OP_ADD_ASSIGN)
			GEN_CASE_TO_STRING(OP_SUB_ASSIGN)
			GEN_CASE_TO_STRING(OP_MUL_ASSIGN)
			GEN_CASE_TO_STRING(OP_DIV_ASSIGN)
			GEN_CASE_TO_STRING(OP_MOD_ASSIGN)
			GEN_CASE_TO_STRING(OP_AND_ASSIGN)
			GEN_CASE_TO_STRING(OP_OR_ASSIGN)
			GEN_CASE_TO_STRING(OP_XOR_ASSIGN)
			GEN_CASE_TO_STRING(OP_LSHIFT_ASSIGN)
			GEN_CASE_TO_STRING(OP_RSHIFT_ASSIGN)
			GEN_CASE_TO_STRING(OP_EQ)
			GEN_CASE_TO_STRING(OP_NEQ)
			GEN_CASE_TO_STRING(OP_GT)
			GEN_CASE_TO_STRING(OP_GTE)
			GEN_CASE_TO_STRING(OP_LT)
			GEN_CASE_TO_STRING(OP_LTE)
			GEN_CASE_TO_STRING(OP_LOGICAL_AND)
			GEN_CASE_TO_STRING(OP_LOGICAL_OR)
			GEN_CASE_TO_STRING(OP_LOGICAL_NOT)
			GEN_CASE_TO_STRING(OP_BIT_AND)
			GEN_CASE_TO_STRING(OP_BIT_OR)
			GEN_CASE_TO_STRING(OP_BIT_XOR)
			GEN_CASE_TO_STRING(OP_BIT_NOT)
			GEN_CASE_TO_STRING(OP_LSHIFT)
			GEN_CASE_TO_STRING(OP_RSHIFT)
			GEN_CASE_TO_STRING(OP_DOT)
			GEN_CASE_TO_STRING(OP_ARROW)
			GEN_CASE_TO_STRING(OP_SCOPE)
			GEN_CASE_TO_STRING(OP_QUESTION)
			GEN_CASE_TO_STRING(OP_COLON)
			GEN_CASE_TO_STRING(OP_COMMA)
			GEN_CASE_TO_STRING(OP_SEMICOLON)
			GEN_CASE_TO_STRING(OP_LPAREN)
			GEN_CASE_TO_STRING(OP_RPAREN)
			GEN_CASE_TO_STRING(OP_LBRACKET)
			GEN_CASE_TO_STRING(OP_RBRACKET)
			GEN_CASE_TO_STRING(OP_LBRACE)
			GEN_CASE_TO_STRING(OP_RBRACE)
			GEN_CASE_TO_STRING(OP_REFERENCE)
			GEN_CASE_TO_STRING(KW_IF)
			GEN_CASE_TO_STRING(KW_ELSE)
			GEN_CASE_TO_STRING(KW_WHILE)
			GEN_CASE_TO_STRING(KW_FOR)
			GEN_CASE_TO_STRING(KW_FUN)
			GEN_CASE_TO_STRING(KW_LET)
			GEN_CASE_TO_STRING(KW_RETURN)
			GEN_CASE_TO_STRING(KW_BREAK)
			GEN_CASE_TO_STRING(KW_CONTINUE)
			GEN_CASE_TO_STRING(TYPE_VOID)
			GEN_CASE_TO_STRING(TYPE_BOOL)
			GEN_CASE_TO_STRING(TYPE_CHAR)
			GEN_CASE_TO_STRING(TYPE_BYTE)
			GEN_CASE_TO_STRING(TYPE_INT)
			GEN_CASE_TO_STRING(TYPE_LONG)
			GEN_CASE_TO_STRING(TYPE_FLOAT)
			GEN_CASE_TO_STRING(TYPE_DOUBLE)
			GEN_CASE_TO_STRING(INVALID)
			GEN_CASE_TO_STRING(UNKNOWN)
		}

		std::stringstream SStr;

		SStr << "Token Kind: " << TypeStr << ", Lexeme: '" << Context.GetTokenLexeme(Lexeme).str() <<
			"', Pos: " << Pos << ", Line: " << Line << ", Column: " << Column;
		return SStr.str();
	}

#undef GEN_CASE_TO_STRING
}